# Generated by Django 6.0.3 on 2026-03-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("nationalite", models.CharField(max_length=50)),
                ("date_naissance", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=20, unique=True)),
                ("date_publication", models.DateField()),
                ("nombre_pages", models.PositiveIntegerField()),
                ("disponible", models.BooleanField(default=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livres",
                        to="gestion.auteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_lecteur", models.CharField(max_length=150)),
                ("date_emprunt", models.DateField()),
                ("date_retour", models.DateField()),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprunts",
                        to="gestion.livre",
                    ),
                ),
            ],
        ),
    ]
