# Generated by Django 6.0.2 on 2026-03-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprunt",
            name="retourne",
            field=models.BooleanField(default=False),
        ),
    ]
